-- AlterTable
ALTER TABLE `transactions` ADD COLUMN `transaction_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `payment_method` ENUM('OTHER', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'BANK_SLIP', 'CASH', 'PIX') NOT NULL;
